spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: Journaldb
      auto-index-creation: true
  radis:
#    host: localhost
#    port: 6379
    uri : ${REDIS_URI}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${USERNAME}
    password: ${PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



server:
  port: 8080
  servlet:
    context-path: /journalapp

weather:
  api:
    key: ${WEATHER_APIKEY}








